config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :subjects
    root "subjects#index"
    resources :questions
    resources :subjects do
      resources :questions
    end
    resources :users
    resources :exams
  end
  root "sessions#new"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "contribute" => "static_pages#contribute"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"
  resources :users do
    root "exams#index"
    resources :exams
    resources :questions
  end
  resources :exams

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_many :exam_questions, dependent: :destroy
  has_many :answers

  scope :alphabet, ->{order :content}
  enum status: {not_confirm: 0, confirmed: 1, rejected: 2}
  enum answer_type: {single_choice: 0, multi_choice: 1, text: 2}

  accepts_nested_attributes_for :answers, allow_destroy: true
  after_create :set_default_status

  validates :content, presence: true
  validates_associated :answers
  validate :validate_answers

  private
  def validate_answers
    unless self.text?
      if answers.size <= Settings.minimum_answer
        errors.add :answers, I18n.t("questions.errors.must_more_one")
      end
      if answers.reject{|answer| !answer.is_correct?}.count == 0
        errors.add :answers, I18n.t("questions.errors.must_has_correct_answer")
      end
    end
  end

  def set_default_status
    if user.admin?
      self.confirmed!
    else
      self.not_confirm!
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :load_subjects, except: [:show]
  before_action :load_question, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.all
    @search = Question.contributed.ransack params[:q]
    @statuses = Question.statuses
    @questions =  @search.result.page(params[:page]).per_page(Settings.pagination.per_page)
  end

  def new
    @question.answers.new
    @subjects = Subject.all
  end

  def create
    @question = current_user.questions.build question_params
    if @question.save
      flash.now[:success] = t "flash.success.created_question"
      redirect_to admin_subject_path @subject
    else
      @subjects = Subject.all
      flash.now[:danger] = t "flash.danger.created_question"
      render :new
    end
  end

  def edit
    @subjects = Subject.all
  end

  def update
    if @question.update_attributes question_params
      flash[:success] = t "flash.danger.edit_question"
      redirect_to admin_subject_questions_path @subject
    else
      @subjects = Subject.all
      flash[:danger] = t "flash.danger.edit_question"
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash.now[:success] = t "flash.success.deleted_question"
    else
      flash[:danger] = t "flash.danger.deleted_question"
    end
    redirect_to :back
  end

  private
  def load_subjects
    @subject =  Subject.find_by id: params[:subject_id]
    unless @subject
      flash[:danger] = t "subject_not_found"
      redirect_to admin_root_path
    end
  end

  def load_question
    @question = @subject.questions.find_by id: params[:id]
    unless @subject
      flash[:danger] = t "subject_not_found"
      redirect_to admin_root_path
    end
  end

  def question_params
    params.require(:question).permit :content, :answer_type, :subject_id,
      :user_id, answers_attributes: [:id, :content, :is_correct, :question_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_all_subject
  before_action :load_question, only: [:destroy, :edit, :update]

  def index
    @questions = current_user.questions.alphabet
      .page(params[:page]).per_page Settings.pagination.per_page
  end

  def new
    @question = current_user.questions.new
    @question.answers.new
  end

  def show
  end

  def create
    @question = current_user.questions.new question_params
    if @question.save
      flash[:success] = t "flash.success.contributed_question"
      redirect_to user_questions_path
    else
      flash[:danger] = t "flash.danger.contributed_question"
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update_attributes question_params
      flash[:success] = t "flash.success.updated_contributed_question"
      redirect_to user_questions_path
    else
      flash[:danger] = t "flash.danger.updated_contributed_question"
      load_all_subject
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = t "flash.success.deleted_contributed_question"
    else
      flash[:danger] = t "flash.danger.deleted_contributed_question"
    end
    redirect_to user_questions_path
  end

  private
  def question_params
    params.require(:question).permit :id, :content, :answer_type,
      :subject_id, answers_attributes: [:id, :content, :is_correct, :_destroy]
  end

  def load_all_subject
    @subjects =  Subject.all
  end

  def load_question
    @question = Question.find_by id: params[:id]
    unless @question
      flash.now[:danger] = t "flash.danger.question_not_found"
      redirect_to question_path
    end
  end
end

app/views/questions/_answer_fields.html.erb
<div class="form-group choice_question">
  <%= f.label t(".answer") %>
  <div class="col-md-12">
    <div class="col-md-8">
      <%= f.text_field :content, label: false, placeholder: t(".answer_content"),
        error: t(".answer_content_error") %>
    </div>
    <div class="col-md-3 space-top-remove">
      <%= f.check_box :is_correct, class: "answers_checkbox" %>
      <%= f.label :is_correct %>
    </div>
    <div class="col-md-1 space-top-remove">
      <%= link_to_remove_fields t(".remove_answer"), f %>
    </div>
  </div>
</div>

app/views/questions/_form.html.erb
<%= form_for [current_user, @question] do |f| %>
  <%= render "shared/error_messages", object: @question %>
  <div class="form-group">
    <%= f.label :subject_id %>
    <%= f.select :subject_id,
      @subjects.collect {|subject| [subject.name, subject.id]},
      {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.text_field :content, placeholder: t(".question_content"),
      error: t(".question_content_error") %>
  </div>
  <div class="form-group">
    <%= f.label :answer_type %>
    <%= f.select :answer_type, Question.answer_types.keys.to_a, {},
      {class: "form-control"} %>
  </div>
  <div id ="answer_field">
    <%= f.fields_for :answers do |answer_builder| %>
      <%= render "answer_fields", f: answer_builder %>
    <% end %>
    <div class="add_fields">
      <%= link_to_add_fields t(".add_answer"), f, :answers %>
    </div>
  </div>
  <%= f.submit yield(:submit_button),
    class: "btn btn-primary space-top-submit" %>
<% end %>

app/views/questions/_list.html.erb
<% @questions.each_with_index do |question, index| %>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= link_to question.content,
      user_question_path(current_user, question) %></td>
    <td><%= question.subject.name %></td>
    <td><%= question.answer_type %></td>
    <td><%= render "shared/question_status_label", question: question %></td>
    <td>
      <%= link_to "", edit_user_question_path(current_user, question),
        class: "glyphicon glyphicon-edit icon-padding link-underline" %>
      <%= link_to "", user_question_path(current_user, question),
        method: :delete, data: {confirm: t(".delete_question_confirm")},
        class: "glyphicon glyphicon-trash icon-padding link-underline" %>
    </td>
  </tr>
<% end %>

app/views/questions/edit.html.erb
<% provide :submit_button, t(".save_changes") %>
<div class="row" id="question">
  <div class="col-md-8 col-md-offset-2">
    <h2><b><%= t ".edit_question" %></b></h2>
    <%= render "form" %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="row" id="question">
  <div class="col-md-10 col-md-offset-1">
    <h2>
      <b><%= t ".suggested_questions" %></b>
      <%= link_to new_user_question_path,
        class: "pull-right link-text-question" do %>
        <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>
        <%= t ".new_question" %>
      <% end %>
    </h2>
    <table class="table table-bordered">
      <thead>
        <tr class="info">
          <th class="number_id"></th>
          <th class="content"><%= t ".question" %></th>
          <th class="subject"><%= t ".subject_name" %></th>
          <th class="type"><%= t ".answer_type" %></th>
          <th class="state"><%= t ".status" %></th>
          <th class="state"><%= t ".actions" %></th>
        </tr>
      </thead>
      <%= render "list" %>
    </table>
  </div>
</div>

app/views/questions/new.html.erb
<div class="row" id="question">
  <div class="col-md-8 col-md-offset-2">
    <h2><b><%= t ".suggest_question" %></b></h2>
    <%= render "form" %>
  </div>
</div>

app/views/questions/show.html.erb
<div id="question" class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2><b><%= t ".question" %></b></h2>
    <table id="table-show">
      <tbody>
        <tr>
          <td><b><%= t ".content" %></b></td>
          <td><%= @question.content %></td>
        </tr>
        <tr>
          <td><b><%= t ".answers" %></b></td>
          <td>
            <table id="table-show-render">
              <tbody>
                <% @question.answers.each do |answer| %>
                  <tr>
                    <td>
                      <%= render "shared/correct_status_label",
                        is_correct: answer.is_correct %>
                    </td>
                    <td></td>
                    <td>
                      <%= answer.content %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </td>
        </tr>
        <tr>
          <td><b><%= t ".subject_name" %></b></td>
          <td><%= @question.subject.name %></td>
        </tr>
        <tr>
          <td><b><%= t ".answer_type" %></b></td>
          <td><%= @question.answer_type %></td>
        </tr>
        <tr>
          <td><b><%= t ".status" %></b></td>
          <td>
            <%= render "shared/question_status_label", question: @question %>
          </td>
        </tr>
        <tr>
          <td><b><%= t ".actions" %></b></td>
          <td>
            <%= link_to t(".edit"),
              edit_user_question_path(current_user, @question),
              class: "btn btn-primary" %>
            <%= link_to t(".delete"),
              user_question_path(current_user, @question),
              method: :delete, data: {confirm: t(".delete_question_confirm")},
              class: "btn btn-danger" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>