config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :subjects
    root "subjects#index"
    resources :questions
    resources :subjects do
      resources :questions
    end
    resources :users
    resources :exams
  end
  root "sessions#new"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "contribute" => "static_pages#contribute"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"
  resources :users do
    root "exams#index"
    resources :exams
    resources :questions
  end
  resources :exams

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user

  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}
  validates :question_number, presence: true,
    numericality: {:only_integer => true, :greater_than_or_equal_to => 0}
  validates :duration, presence: true, numericality: {only_integer: true}
  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :load_subject, except: [:index, :new, :create]
  before_action :verify_admin

  def index
    @subjects = Subject.newest.paginate page: params[:page],
      per_page: Settings.pagination.per_page
  end

  def new
    @subject = current_user.subjects.new
  end

  def show
  end

  def create
    @subject = current_user.subjects.new subject_params
    if @subject.save
      flash.now[:susscess] = "flash.susscess.create_subject"
      redirect_to admin_subjects_path
    else
      flash.now[:danger] = t "flash.danger.created_subject"
      render :new
    end
  end

  def update
    if @subject.update_attributes subject_params
      flash.now[:success] = t "flash.success.updated_subject"
    else
      flash.now[:danger] = t "flash.danger.updated_subject"
    end
    redirect_to admin_subjects_path
  end

  def destroy
    if @subject.destroy
      flash.now[:success] = t "flash.success.deleted_subject"
    else
      flash.now[:danger] = t "flash.danger.deleted_subject"
    end
    redirect_to admin_subjects_path
  end

  def edit
  end

  private
  def subject_params
    params.require(:subject).permit :name, :question_number, :duration
  end

  def load_subject
    @subject = Subject.find_by id: params[:id]
    unless @subject
      flash.now[:danger] = t "flash.danger.subject_not_found"
      redirect_to admin_subjects_path
    end
  end
end

app/views/admin/subjects/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h1><%= yield(:modal_title) %></h1>
    </div>
    <%= form_for [:admin, @subject] do |f| %>
      <div class="modal-body">
         <div class="form_errors">
            <%= render "shared/error_messages", object: @subject %>
         </div>
         <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
         </div>
         <div class="form-group">
            <%= f.label :question_number %>
            <%= f.text_field :question_number, class: "form-control" %>
         </div>
         <div class="form-group">
            <%= f.label :duration %>
            <%= f.text_field :duration, class: "form-control" %>
         </div>
      </div>
      <div class="modal-footer">
         <span class="pull-right">
            <%= f.submit t("creates"), class: "btn btn-primary" %>
         </span>
         <span class="pull-left">
            <%= link_to t(".cancel_button"), admin_subjects_path, class: "btn btn-warning",data: {dismiss: "modal"} %>
         </span>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/subjects/_subjects.html.erb
<% @subjects.each do |subject| %>
  <tr>
    <td><%= link_to subject.name, [:admin, subject] %></td>
    <td><%= subject.question_number %></td>
    <td><%= subject.duration %></td>
    <td>
      <%= link_to t(".edit"), edit_admin_subject_path(subject.id),
        class: "btn btn-primary" %>
      <%= link_to t(".delete"), admin_subject_path(subject.id),
        method: :delete, data: {confirm: t(".delete_subject_confirm")},
        class: "btn btn-danger" %>
    </td>
  </tr>
<% end %>

app/views/admin/subjects/edit.html.erb
<% provide :modal_title, t(".edit_subject") %>
<% provide :submit_button, t(".save_button") %>
<%= render "form" %>

app/views/admin/subjects/index.html.erb
<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-12">
    <%= link_to t(".new_subject"), new_admin_subject_path,
    class: "btn btn-primarys" %>
  </div>
</div>
<div class="row">
  <table class="table table-bordered table-striped">
    <thead>
      <tr class="info">
        <th><%= t ".name" %></th>
        <th><%= t ".question_number" %></th>
        <th><%= t ".duration" %></th>
        <th><%= t ".actions" %></th>
      </tr>
    </thead>
    <tbody class="subject-index">
      <%= render "subjects" %>
    </tbody>
  </table>
  <%= will_paginate @subjects %>
  <div id="subject-modal" class="modal fade"></div>
</div>

app/views/admin/subjects/new.html.erb
<% provide :modal_title, t(".create_subject") %>
<% provide :submit_button, t(".create_button") %>
<%= render "form" %>

app/views/admin/subjects/show.html.erb
<h1><%= @subject.name %></h1>
<div class="row center">
  <div class="col-md-12">
    <%= link_to t(".new_question"), new_admin_subject_question_path(@subject),
    class: "btn btn-primarys" %>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% @subject.questions.each_with_index do |question, index| %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <%= "#{index + 1}. #{question.content}" %>
        </div>
        <div class="panel-body">
          <% question.answers.each do |answer| %>
            <div class="row">
              <div class="col-md-2">
                <%= render "shared/correct_status_label",
                  is_correct: answer.is_correct unless question.text? %>
              </div>
              <div class="col-md-10">
                <%= answer.content %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-4">
              <%= link_to t(".edit_button"),
                edit_admin_subject_question_path(@subject, question),
                class: "btn btn-success btn-block" %>
            </div>
            <div class="col-md-4 col-md-offset-4">
              <%= link_to t(".delete_button"),
                admin_subject_question_path(@subject, question),
                method: :delete, class: "btn btn-danger btn-block",
                data: {confirm: t(".delete_question_confirm")} %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>