config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :subjects
    root "subjects#index"
    resources :questions
    resources :subjects do
      resources :questions
    end
    resources :users
    resources :exams
  end
  root "sessions#new"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "contribute" => "static_pages#contribute"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"
  resources :users do
    root "exams#index"
    resources :exams
    resources :questions
  end
  resources :exams

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_many :exam_questions, dependent: :destroy
  has_many :answers

  scope :alphabet, ->{order :content}
  enum status: {not_confirm: 0, confirmed: 1, rejected: 2}
  enum answer_type: {single_choice: 0, multi_choice: 1, text: 2}

  accepts_nested_attributes_for :answers, allow_destroy: true
  after_create :set_default_status

  validates :content, presence: true
  validates_associated :answers
  validate :validate_answers

  private
  def validate_answers
    unless self.text?
      if answers.size <= Settings.minimum_answer
        errors.add :answers, I18n.t("questions.errors.must_more_one")
      end
      if answers.reject{|answer| !answer.is_correct?}.count == 0
        errors.add :answers, I18n.t("questions.errors.must_has_correct_answer")
      end
    end
  end

  def set_default_status
    if user.admin?
      self.confirmed!
    else
      self.not_confirm!
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :load_subjects, except: [:show]
  before_action :load_question, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.all
    @search = Question.contributed.ransack params[:q]
    @statuses = Question.statuses
    @questions =  @search.result.page(params[:page]).per_page(Settings.pagination.per_page)
  end

  def new
    @question.answers.new
    @subjects = Subject.all
  end

  def create
    @question = current_user.questions.build question_params
    if @question.save
      flash.now[:success] = t "flash.success.created_question"
      redirect_to admin_subject_path @subject
    else
      @subjects = Subject.all
      flash.now[:danger] = t "flash.danger.created_question"
      render :new
    end
  end

  def edit
    @subjects = Subject.all
  end

  def update
    if @question.update_attributes question_params
      flash[:success] = t "flash.danger.edit_question"
      redirect_to admin_subject_questions_path @subject
    else
      @subjects = Subject.all
      flash[:danger] = t "flash.danger.edit_question"
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash.now[:success] = t "flash.success.deleted_question"
    else
      flash[:danger] = t "flash.danger.deleted_question"
    end
    redirect_to :back
  end

  private
  def load_subjects
    @subject =  Subject.find_by id: params[:subject_id]
    unless @subject
      flash[:danger] = t "subject_not_found"
      redirect_to admin_root_path
    end
  end

  def load_question
    @question = @subject.questions.find_by id: params[:id]
    unless @subject
      flash[:danger] = t "subject_not_found"
      redirect_to admin_root_path
    end
  end

  def question_params
    params.require(:question).permit :content, :answer_type, :subject_id,
      :user_id, answers_attributes: [:id, :content, :is_correct, :question_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_all_subject
  before_action :load_question, only: [:destroy, :edit, :update]

  def index
    @questions = current_user.questions.alphabet
      .page(params[:page]).per_page Settings.pagination.per_page
  end

  def new
    @question = current_user.questions.new
    @question.answers.new
  end

  def show
  end

  def create
    @question = current_user.questions.new question_params
    if @question.save
      flash[:success] = t "flash.success.contributed_question"
      redirect_to user_questions_path
    else
      flash[:danger] = t "flash.danger.contributed_question"
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update_attributes question_params
      flash[:success] = t "flash.success.updated_contributed_question"
      redirect_to user_questions_path
    else
      flash[:danger] = t "flash.danger.updated_contributed_question"
      load_all_subject
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = t "flash.success.deleted_contributed_question"
    else
      flash[:danger] = t "flash.danger.deleted_contributed_question"
    end
    redirect_to user_questions_path
  end

  private
  def question_params
    params.require(:question).permit :id, :content, :answer_type,
      :subject_id, answers_attributes: [:id, :content, :is_correct, :_destroy]
  end

  def load_all_subject
    @subjects =  Subject.all
  end

  def load_question
    @question = Question.find_by id: params[:id]
    unless @question
      flash.now[:danger] = t "flash.danger.question_not_found"
      redirect_to question_path
    end
  end
end

app/views/admin/questions/_answer_fields.html.erb
<div class="form-group choice_question">
  <%= f.label t(".answer") %>
  <div class="col-md-12">
    <div class="col-md-8">
      <%= f.text_field :content, label: false,
       placeholder: t(".answer_content"),error: t(".answer_content_error") %>
    </div>
    <div class="col-md-3 space-top-remove">
      <%= f.check_box :is_correct, class: "answers_checkbox" %>
      <%= f.label :is_correct %>
    </div>
    <div class="col-md-1 space-top-remove">
      <%= link_to_remove_fields t(".remove_answer"), f %>
    </div>
  </div>
</div>

app/views/admin/questions/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content" id="question">
    <div class="modal-header"><h1><%= yield :modal_title %></h1></div>
    <%= form_for [:admin, @subject, @question] do |f| %>
      <div class="modal-body">
        <div class="form_errors">
          <%= render "shared/error_messages", object: @question %>
        </div>
        <div class="form-group">
          <%= f.label :subject_id %>
          <%= text_field_tag :subject_name, @subject.name, disabled: true %>
          <%= f.hidden_field :subject_id, value: @subject.id %>
        </div>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_field :content, placeholder: t(".question_content"),
            error: t(".question_content_error") %>
        </div>
        <div class="form-group">
          <%= f.label :type %>
          <%= f.select :answer_type, Question.answer_types.keys.to_a, {},
          {class: "form-control"} %>
        </div>
        <div id ="answers_field">
          <%= f.fields_for :answers do |answer_builder| %>
            <%= render "answer_fields", f: answer_builder %>
          <% end %>
          <div id ="answer_field">
          </div>
          <div class="add_fields">
            <%= link_to_add_fields t(".add_answer"), f, :answers %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <span class="pull-right">
          <%= f.submit t("submit_button"), class: "btn btn-primary" %>
        </span>
        <span class="pull-left">
          <%= link_to t(".cancel_button"), :back, class: "btn btn-warning",
            data: {dismiss: "modal"} %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/questions/_question.html.erb
<tr>
  <td class="center"><%= question.content %></td>
  <td class="center"><%= question.subject.name %></td>
  <td class="center"><%= question.user.name %></td>
  <td class="center"><%= time_tag question.created_at %></td>
  <td class="center"><%= t question.status  %></td>
  <td class="center">
    <%= link_to t("suggested_question.check"),
      edit_admin_question_path(question), class: "btn btn-info" %>
  </td>
</tr>

app/views/admin/questions/_question_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <div>
        <%= t "question.question" %>
        <%= @question.content %>
      </div>
      <div>
        <%= t "question.type" %>
        <%= t question.answer_type %>
      </div>
      <div>
        <%= t "question.status" %>:
      <%= t question.status %>
      </div>
    </div>
  </div>
  <div>
    <% question.answers.each do |answer| %>
      <div class ="checkbox">
        <label>
          <%= check_box_tag answer.content, answer.is_correct? ?
            "yes" : "no", true, disabled: true %>
          <%= answer.content %>
        </label>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/questions/_search_form.html.erb
<div class="center row">
  <%= search_form_for @search, url: admin_questions_path do |f| %>
    <div class="col-md-3">
      <%= t "search.user.name" %>
      <%= f.text_field :content_cont, class: "form-control" %>
    </div>
    <div class="col-md-5">
      <%= t "search.subject" %>
      <%= f.collection_select :subject_id_eq, @subjects,
        :id, :name, {include_blank: t("all")}, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <br />
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/questions/edit.html.erb
<% provide :modal_title, t(".edit_question") %>
<% provide :submit_button, t(".save_button") %>
<% provide :title, t("title") %>
<%= render "form" %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <%= t ".confirm" %>
      </div>
      <div class="panel-body">
      <% Settings.questions.status.each do |key, value| %>
        <%= link_to admin_question_path(@question,
          question: {status: key}), method: :put, class: "button" do %>
          <%= t value %>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/questions/index.html.erb
<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-12">
    <%= link_to t(".new_question"), new_admin_subject_question_path(@subject),
    class: "btn btn-primarys" %>
  </div>
</div>
<div class="row">
  <table class="table table-bordered table-striped">
    <thead>
      <tr class="info">
        <th><%= t ".content" %></th>
        <th><%= t ".subject" %></th>
        <th><%= t ".type_answer" %></th>
        <th><%= t ".create_date" %></th>
        <th><%= t ".confirmed" %></th>
        <th><%= t ".actions" %></th>
      </tr>
    </thead>
    <tbody class="subject-index">
      <%= render "question" %>
    </tbody>
  </table>
  <%= will_paginate @questions %>
  <div id="question-modal" class="modal fade"></div>
</div>

app/views/admin/questions/new.html.erb
<% provide :modal_title, t(".create_question") %>
<% provide :submit_button, t(".create_button") %>
<%= render "form" %>