config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :subjects
    root "subjects#index"
    resources :questions
    resources :subjects do
      resources :questions
    end
    resources :users
    resources :exams
  end
  root "sessions#new"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "contribute" => "static_pages#contribute"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"
  resources :users do
    root "exams#index"
    resources :exams
    resources :questions
  end
  resources :exams

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a><%= t "iteam" %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("help"), help_path %></li>
      <li><%= link_to t("about"), about_path %></li>
      <li><%= link_to t("contact"), contact_path %></li>
      <li><%= link_to t("news"), Settings.framgialink %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="header">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav navbar-right menu">
        <% if logged_in? %>
          <li><%= link_to t("home"), user_exams_path(current_user) %></li>
          <li><%= link_to t("contribute"), user_questions_path(current_user) %></li>
          <% if current_user.admin? %>
            <li><%= link_to t("users"), admin_users_path %></li>
            <li><%= link_to t("subjects"), admin_subjects_path %></li>
            <li><%= link_to t("admin_exams"), admin_exams_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login"), login_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to t("name_system") , root_path %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
      <div class="col-md-12">
        <%= render "layouts/footer" %>
      </div>
    </div>
  </body>
</html>